# Deploys hub scaffolding for the specified environment

parameters:
  - name: deployRgp
    displayName: 'deploy Resource Groups'
    type: boolean
    default: true
  - name: deployLws
    displayName: 'deploy Log Analytics Workspace'
    type: boolean
    default: true
  - name: deployUdr
    displayName: 'deploy UDRs'
    type: boolean
    default: true
  - name: deployNsg
    displayName: 'deploy NSGs'
    type: boolean
    default: true
  - name: deployVnt
    displayName: 'deploy VNET'
    type: boolean
    default: true
  - name: deployAkv
    displayName: 'deploy Key Vaults'
    type: boolean
    default: true
  - name: deploySta
    displayName: 'deploy Storage Accounts'
    type: boolean
    default: true
  - name: deployNsf
    displayName: 'deploy NSG Flow Logs'
    type: boolean
    default: true
  - name: deployAua
    displayName: 'deploy Automation Account'
    type: boolean
    default: true
  - name: deployPip
    displayName: 'deploy Public IP Prefix'
    type: boolean
    default: true
  - name: deployPia
    displayName: 'deploy Public IP Addresses'
    type: boolean
    default: true
  - name: deployAfw
    displayName: 'deploy Firewall'
    type: boolean
    default: true

trigger: none

pool:
  name: Azure Pipelines
  vmImage: 'windows-2019'

variables:
- group: HubScaffolding

steps:
- checkout: self
  fetchDepth: 1

- task: AzurePowerShell@5
  displayName: 'Azure AD Group Creation'
  inputs:
    azureSubscription: 'FGT-ROOT-MGP-OWNR'
    ScriptPath: scaffolding/createAkvAadGroups.ps1
    ScriptArguments: '-EnterprisePrefix $(EnterprisePrefix) -SubscriptionOrdinalPrefix $(SubscriptionOrdinalPrefix)'
    azurePowerShellVersion: LatestVersion

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Hub Scaffolding Deployment'
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'FGT-ROOT-MGP-OWNR'
    subscriptionid: '$(subscriptionId)'
    location: '$(location)'
    csmFile: 'scaffolding/hubScaffolding_armTemplate.json'
    overrideParameters: '-addressPrefixes $(addressPrefixes)
                         -allowedOnPremsPublicIps $(allowedOnPremsPublicIps)
                         -applicationTag $(applicationTag)
                         -dnsServers $(dnsServers)
                         -EnterprisePrefix $(EnterprisePrefix)
                         -EnvironmentPrefix $(EnvironmentPrefix)
                         -environmentTag $(environmentTag)
                         -keyVaultFullAccessGroupId $(keyVaultFullAccessGroupId)
                         -keyVaultReadOnlyAccessGroupId $(keyVaultReadOnlyAccessGroupId)
                         -location $(location)
                         -logWkslocation $(logWkslocation)
                         -LogWksRegionPrefix $(LogWksRegionPrefix)
                         -RegionPrefix $(RegionPrefix)
                         -subnetPrefixAG $(subnetPrefixAG)
                         -subnetPrefixAP $(subnetPrefixAP)
                         -subnetPrefixDS $(subnetPrefixDS)
                         -subnetPrefixFS $(subnetPrefixFS)
                         -subnetPrefixFW $(subnetPrefixFW)
                         -subnetPrefixJP $(subnetPrefixJP)
                         -subnetPrefixRP $(subnetPrefixRP)
                         -subnetPrefixVG $(subnetPrefixVG)
                         -subscriptionId $(subscriptionId)
                         -SubscriptionOrdinalPrefix $(SubscriptionOrdinalPrefix)
                         -tenantId $(tenantId)
                         -deployAfw ${{ parameters.deployAfw }}
                         -deployAkv ${{ parameters.deployAkv }}
                         -deployAua ${{ parameters.deployAua }}
                         -deployLws ${{ parameters.deployLws }}
                         -deployNsf ${{ parameters.deployNsf }}
                         -deployNsg ${{ parameters.deployNsg }}
                         -deployPia ${{ parameters.deployPia }}
                         -deployPip ${{ parameters.deployPip }}
                         -deployRgp ${{ parameters.deployRgp }}
                         -deploySta ${{ parameters.deploySta }}
                         -deployUdr ${{ parameters.deployUdr }}
                         -deployVnt ${{ parameters.deployVnt }}'