# Deploys hub scaffolding for the specified environment

trigger: none

pool:
  name: Azure Pipelines
  vmImage: 'windows-2019'

variables:
- group: Hub

steps:
- checkout: self
  fetchDepth: 1

- task: AzurePowerShell@5
displayName: 'Management Group Creation'
inputs:
  azureSubscription: 'FGT-ROOT-MGP-OWNR'
  ScriptPath: scaffolding/createMgp.ps1
  ScriptArguments: '-EnterprisePrefix $(EnterprisePrefix) -ManagementGroupNamePrefix $(ManagementGroupNamePrefix) -SubscriptionNamePrefix $(SubscriptionNamePrefix) -SubscriptionOrdinalPrefix $(SubscriptionOrdinalPrefix) -ParentMgpResourceId $(ParentMgpResourceId)'
  azurePowerShellVersion: LatestVersion