# Deploys hub scaffolding for the specified environment

trigger: none

pool:
  name: Azure Pipelines
  vmImage: 'windows-2019'

variables:
- group: Hub

steps:
- checkout: self
  fetchDepth: 1

- task: AzurePowerShell@5
  displayName: 'Management Group Creation'
  inputs:
    azureSubscription: 'FGT-ROOT-MGP-OWNR'
    ScriptPath: scaffolding/createMgp.ps1
    ScriptArguments: '-EnterprisePrefix $(EnterprisePrefix) -ManagementGroupNamePrefix $(ManagementGroupNamePrefix) -SubscriptionNamePrefix $(SubscriptionNamePrefix) -SubscriptionOrdinalPrefix $(SubscriptionOrdinalPrefix) -ParentMgpResourceId $(ParentMgpResourceId)'
    azurePowerShellVersion: LatestVersion

- task: AzurePowerShell@5
  displayName: 'AAD Groups Creation'
  inputs:
    azureSubscription: 'FGT-ROOT-MGP-OWNR'
    ScriptPath: scaffolding/createAadGroups.ps1
    ScriptArguments: '-EnterprisePrefix $(EnterprisePrefix) -ManagementGroupNamePrefix $(ManagementGroupNamePrefix) -SubscriptionNamePrefix $(SubscriptionNamePrefix) -SubscriptionOrdinalPrefix $(SubscriptionOrdinalPrefix)'
    azurePowerShellVersion: LatestVersion

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Hub Scaffolding Deployment'
  inputs:
    deploymentScope: 'Management Group'
    azureResourceManagerConnection: 'FGT-ROOT-MGP-OWNR'
    location: '$(location)'
    csmFile: 'scaffolding/hubScaffolding_armTemplate.json'
    overrideParameters: '-mgpName $(mgpName) -mgpRbacReaderGroupId $(mgpRbacReaderGroupId) -mgpRbacContributorGroupId $(mgpRbacContributorGroupId) -mgpRbacOwnerGroupId $(mgpRbacOwnerGroupId)'