# Deploys hub scaffolding for the specified environment

trigger: none

pool:
  name: Azure Pipelines
  vmImage: 'windows-2019'

variables:
- group: HubScaffolding

steps:
- checkout: self
  fetchDepth: 1

- task: AzurePowerShell@5
  displayName: 'Azure AD Group Creation'
  inputs:
    azureSubscription: 'FGT-ROOT-MGP-OWNR'
    ScriptPath: scaffolding/createAkvAadGroups.ps1
    ScriptArguments: '-EnterprisePrefix $(EnterprisePrefix) -SubscriptionOrdinalPrefix $(SubscriptionOrdinalPrefix)'
    azurePowerShellVersion: LatestVersion

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Hub Scaffolding Deployment'
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'FGT-ROOT-MGP-OWNR'
    subscriptionid: '$(subscriptionId)'
    location: '$(location)'
    csmFile: 'scaffolding/hubScaffolding_armTemplate.json'
    overrideParameters: '-addressPrefixes $(addressPrefixes)
                         -allowedOnPremsPublicIps $(allowedOnPremsPublicIps)
                         -applicationTag $(applicationTag)
                         -dnsServers $(dnsServers)
                         -EnterprisePrefix $(EnterprisePrefix)
                         -EnvironmentPrefix $(EnvironmentPrefix)
                         -environmentTag $(environmentTag)
                         -keyVaultFullAccessGroupId $(keyVaultFullAccessGroupId)
                         -keyVaultReadOnlyAccessGroupId $(keyVaultReadOnlyAccessGroupId)
                         -location $(location)
                         -logWkslocation $(logWkslocation)
                         -LogWksRegionPrefix $(LogWksRegionPrefix)
                         -RegionPrefix $(RegionPrefix)
                         -subnetPrefixAG $(subnetPrefixAG)
                         -subnetPrefixAP $(subnetPrefixAP)
                         -subnetPrefixDS $(subnetPrefixDS)
                         -subnetPrefixFS $(subnetPrefixFS)
                         -subnetPrefixFW $(subnetPrefixFW)
                         -subnetPrefixJP $(subnetPrefixJP)
                         -subnetPrefixRP $(subnetPrefixRP)
                         -subnetPrefixVG $(subnetPrefixVG)
                         -subscriptionId $(subscriptionId)
                         -SubscriptionOrdinalPrefix $(SubscriptionOrdinalPrefix)
                         -tenantId $(tenantId)'