# Deploys hub scaffolding for the specified environment

trigger: none

pool:
  name: Azure Pipelines
  vmImage: 'windows-2019'

variables:
- group: HubScaffolding

steps:
- checkout: self
  fetchDepth: 1

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Hub Scaffolding Deployment'
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'FGT-ROOT-MGP-OWNR'
    subscription: '$(subscriptionId)'
    location: '$(location)'
    csmFile: 'scaffolding/hubScaffolding_armTemplate.json'
    overrideParameters: '-addressPrefixes $(addressPrefixes)
                         -addsSubnetPrefix $(addsSubnetPrefix)
                         -adfsSubnetPrefix $(adfsSubnetPrefix)
                         -allowedOnPremsPublicIps $(allowedOnPremsPublicIps)
                         -appGatewaySubnetPrefix $(appGatewaySubnetPrefix)
                         -applicationTag $(applicationTag)
                         -appSubnetPrefix $(appSubnetPrefix)
                         -dnsServers $(dnsServers)
                         -EnterprisePrefix $(EnterprisePrefix)
                         -EnvironmentPrefix $(EnvironmentPrefix)
                         -environmentTag $(environmentTag)
                         -firewallSubnetPrefix $(firewallSubnetPrefix)
                         -gatewaySubnetPrefix $(gatewaySubnetPrefix)
                         -jumpSrvSubnetPrefix $(jumpSrvSubnetPrefix)
                         -keyVaultFullAccessGroupId $(keyVaultFullAccessGroupId)
                         -keyVaultReadOnlyAccessGroupId $(keyVaultReadOnlyAccessGroupId)
                         -location $(location)
                         -logWkslocation $(logWkslocation)
                         -LogWksRegionPrefix $(LogWksRegionPrefix)
                         -RegionPrefix $(RegionPrefix)
                         -subscriptionId $(subscriptionId)
                         -SubscriptionOrdinalPrefix $(SubscriptionOrdinalPrefix)
                         -tenantId $(tenantId)
                         -wapSubnetPrefix $(wapSubnetPrefix)'