# Deploys indicated VM resources to target subsription

parameters:
  - name: nsgTierList
    displayName: 'Network Security Group Tiers to update'
    type: object
    default:
      - ap
      - db 
      - ds
      - ed
      - fs
      - jp
      - rp

trigger: none

pool:
  name: Azure Pipelines
  vmImage: 'windows-2019'

variables:
- group: HubScaffolding

jobs:
  - ${{ each nsgTier in parameters.nsgTierList }}:
    - job: "${{ nsgTier }}_NSG"

      steps:
        - checkout: self
          fetchDepth: 1

        # Deploy Azure Resources using ARM template
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: "Deploy ${{ nsgTier }} NSG"
          enabled: true
          continueOnError: true
          inputs:            
            deploymentScope: 'Subscription'
            azureResourceManagerConnection: 'FGT-ROOT-MGP-OWNR'
            subscriptionid: '$(subscriptionId)'
            location: '$(location)'
            csmFile: "nsg/nsgSecRules_armTemplate.json"            
            csmParametersFile: "nsg/securityRules_${{ nsgTier }}.json"    
            overrideParameters: '-allowedOnPremsPublicIps $(allowedOnPremsPublicIps)
                                 -applicationTag $(applicationTag)
                                 -dnsServers $(dnsServers)
                                 -EnterprisePrefix $(EnterprisePrefix)
                                 -EnvironmentPrefix $(EnvironmentPrefix)
                                 -environmentSupernet $(environmentSupernet)
                                 -environmentTag $(environmentTag)  
                                 -LogWksRegionPrefix $(LogWksRegionPrefix)
                                 -RegionPrefix $(RegionPrefix)
                                 -subnetPrefixAG $(subnetPrefixAG)
                                 -subnetPrefixAP $(subnetPrefixAP)
                                 -subnetPrefixDS $(subnetPrefixDS)
                                 -subnetPrefixFS $(subnetPrefixFS)
                                 -subnetPrefixFW $(subnetPrefixFW)
                                 -subnetPrefixJP $(subnetPrefixJP)
                                 -subnetPrefixRP $(subnetPrefixRP)
                                 -subnetPrefixVG $(subnetPrefixVG)
                                 -SubscriptionOrdinalPrefix $(SubscriptionOrdinalPrefix)
                                 -nsgTier ${{ nsgTier }}'