# Deploys indicated VM resources to target subsription

parameters:
  - name: nsgTierList
    displayName: 'Network Security Group Tiers to update'
    type: object
    default:
      - ap
      - db 
      - ds
      - ed
      - fs
      - jp
      - rp

trigger: none

pool:
  name: Azure Pipelines
  vmImage: 'windows-2019'

variables:
- group: HubScaffolding

jobs:
  - ${{ each nsgTier in parameters.nsgTierList }}:
    - job: "${{ nsgTier }}_NSG"

      steps:
        - checkout: self
          fetchDepth: 1

        # Deploy Azure Resources using ARM template
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: "Deploy ${{ nsgTier }} NSG"
          enabled: true
          continueOnError: true
          inputs:            
            deploymentScope: 'Subscription'
            azureResourceManagerConnection: 'FGT-ROOT-MGP-OWNR'
            subscriptionid: '$(subscriptionId)'
            location: '$(location)'
            csmFile: "nsg/${{ nsgTier }}_nsg_armTemplate.json"
            overrideParameters: '-addsSubnetPrefix $(addsSubnetPrefix)
                                 -adfsSubnetPrefix $(adfsSubnetPrefix)
                                 -allowedOnPremsPublicIps $(allowedOnPremsPublicIps)
                                 -appGatewaySubnetPrefix $(appGatewaySubnetPrefix)
                                 -applicationTag $(applicationTag)
                                 -appSubnetPrefix $(appSubnetPrefix)
                                 -dnsServers $(dnsServers)
                                 -EnterprisePrefix $(EnterprisePrefix)
                                 -EnvironmentPrefix $(EnvironmentPrefix)
                                 -environmentTag $(environmentTag)                                
                                 -jumpSrvSubnetPrefix $(jumpSrvSubnetPrefix)
                                 -LogWksRegionPrefix $(LogWksRegionPrefix)
                                 -RegionPrefix $(RegionPrefix)
                                 -SubscriptionOrdinalPrefix $(SubscriptionOrdinalPrefix)
                                 -wapSubnetPrefix $(wapSubnetPrefix)'